version: '3.1'

services:

  db:
    image: postgres:11.2-alpine
    container_name: tr_psql
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - /var/tr-postgres-data:/var/lib/postgresql/data

